version: "3.9"

services:
  # ---------- Databases ----------
  user_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: userdb
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    restart: unless-stopped

  course_db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: coursedb
    ports:
      - "5435:5432"
    volumes:
      - course_data:/var/lib/postgresql/data
    restart: unless-stopped

  # ---------- Microservices ----------
  user_service:
    build: ./user_service
    env_file: ./user_service/.env.docker
    environment:
      APP_ENV: docker
    depends_on:
      - user_db
    ports:
      - "8001:8000"
    restart: unless-stopped

  course_service:
    build: ./course_service
    env_file: ./course_service/.env.docker
    environment:
      APP_ENV: docker
    depends_on:
      - course_db
    ports:
      - "8002:8000"
    restart: unless-stopped

volumes:
  user_data:
  course_data:
